version: "3.1"

volumes:
  db-data:

services:
  postgres:
    image: postgres:11.7-alpine
    network_mode: host
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=devtips_bot.password"
